DELETE FROM `kanrensha_person_history_01`;
DELETE FROM `kanrensha_person_history_02`;
DELETE FROM `kanrensha_person_history_03`;
DELETE FROM `kanrensha_person_history_04`;
DELETE FROM `kanrensha_person_history_05`;
DELETE FROM `kanrensha_person_history_06`;
DELETE FROM `kanrensha_person_history_07`;
DELETE FROM `kanrensha_person_history_08`;
DELETE FROM `kanrensha_person_history_09`;
DELETE FROM `kanrensha_person_history_10`;
DELETE FROM `kanrensha_person_history_11`;
DELETE FROM `kanrensha_person_history_12`;
DELETE FROM `kanrensha_person_history_13`;
DELETE FROM `kanrensha_person_history_14`;
DELETE FROM `kanrensha_person_history_15`;
DELETE FROM `kanrensha_person_history_16`;
DELETE FROM `kanrensha_person_history_17`;
DELETE FROM `kanrensha_person_history_18`;
DELETE FROM `kanrensha_person_history_19`;
DELETE FROM `kanrensha_person_history_20`;
DELETE FROM `kanrensha_person_history_21`;
DELETE FROM `kanrensha_person_history_22`;
DELETE FROM `kanrensha_person_history_23`;
DELETE FROM `kanrensha_person_history_24`;
DELETE FROM `kanrensha_person_history_25`;
DELETE FROM `kanrensha_person_history_26`;
DELETE FROM `kanrensha_person_history_27`;
DELETE FROM `kanrensha_person_history_28`;
DELETE FROM `kanrensha_person_history_29`;
DELETE FROM `kanrensha_person_history_30`;
DELETE FROM `kanrensha_person_history_31`;
DELETE FROM `kanrensha_person_history_32`;
DELETE FROM `kanrensha_person_history_33`;
DELETE FROM `kanrensha_person_history_34`;
DELETE FROM `kanrensha_person_history_35`;
DELETE FROM `kanrensha_person_history_36`;
DELETE FROM `kanrensha_person_history_37`;
DELETE FROM `kanrensha_person_history_38`;
DELETE FROM `kanrensha_person_history_39`;
DELETE FROM `kanrensha_person_history_40`;
DELETE FROM `kanrensha_person_history_41`;
DELETE FROM `kanrensha_person_history_42`;
DELETE FROM `kanrensha_person_history_43`;
DELETE FROM `kanrensha_person_history_44`;
DELETE FROM `kanrensha_person_history_45`;
DELETE FROM `kanrensha_person_history_46`;
DELETE FROM `kanrensha_person_history_47`;
DELETE FROM `kanrensha_person_history_99`;

ALTER TABLE `kanrensha_person_history_01` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_02` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_03` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_04` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_05` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_06` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_07` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_08` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_09` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_10` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_11` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_12` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_13` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_14` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_15` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_16` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_17` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_18` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_19` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_20` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_21` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_22` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_23` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_24` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_25` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_26` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_27` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_28` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_29` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_30` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_31` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_32` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_33` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_34` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_35` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_36` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_37` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_38` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_39` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_40` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_41` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_42` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_43` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_44` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_45` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_46` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_47` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_99` auto_increment = 0;
