CREATE TABLE `kanrensha_kigyou_dt_history_42` (
  `kanrensha_kigyou_dt_history_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kigyou_dt_kanrensha_code` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '企業団体関連者コード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新フラグ',
  `all_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '関連者企業・団体名',
  `all_address` text COLLATE utf8mb4_bin COMMENT '関連者企業・団体全住所',
  `org_delegate_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '団体代表者氏名',
  `org_delegate_code` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '団体代表者関連者個人コード',
  `search_text` text COLLATE utf8mb4_bin COMMENT '検索テキスト',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザーId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '削除ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '削除ユーザコード',
  `delete_user_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '削除ユーザ名',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '削除日時',
  PRIMARY KEY (`kanrensha_kigyou_dt_history_id`),
  FULLTEXT KEY `search_text_index` (`search_text`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
