CREATE TABLE `kanrensha_seijidantai_address` (
  `kanrensha_seijidantai_address_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kanrensha_seijidantai_id` int DEFAULT NULL COMMENT '関連者政治団体Id',
  `seijidantai_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者政治団体コード',
  `kanrensha_name` varchar(200) DEFAULT NULL COMMENT '関連者政治団体名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
    postalcode1 varchar(100) COMMENT '郵便番号1',
    postalcode2 varchar(100) COMMENT '郵便番号2',
    addressPostal varchar(100) COMMENT '住所郵便番号まで',
    addressBlock varchar(100) COMMENT '住所番地',
    addressBuilding varchar(100) COMMENT '住所建物',
    lgCode varchar(100) COMMENT '地方公共団体コード',
    machiazaId varchar(100) COMMENT '町字Id',
    blkId varchar(100) COMMENT '街区Id',
    prcId varchar(100) COMMENT '地番Id',
    rsdtId varchar(100) COMMENT '住居Id',
    rsdt2Id varchar(100) COMMENT '住居2Id',
    isPostalEdit tinyint COMMENT '住所郵便番号まで編集有無',
    isBlockEdit tinyint COMMENT '住所番地編集有無',
    isBuildingEdit tinyint COMMENT '住所建物編集有無',
 `is_postal_accept` tinyint DEFAULT NULL COMMENT '住所郵便番号承認該否',
  `is_block_accept` tinyint DEFAULT NULL COMMENT '住所番地承認該否',
  `is_building_accept` tinyint DEFAULT NULL COMMENT '住所建物承認該否',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_seijidantai_address_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
