CREATE TABLE `kanrensha_seijidantai_property` (
  `kanrensha_seijidantai_property_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kanrensha_seijidantai_id` int DEFAULT NULL COMMENT '関連者政治団体Id',
  `seijidantai_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者政治団体コード',
  `kanrensha_name` varchar(200) DEFAULT NULL COMMENT '関連者政治団体名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `org_name_kana` varchar(200) DEFAULT NULL COMMENT '関連者団体名称かな',
  `org_delegate_code` varchar(200) DEFAULT NULL COMMENT '団体代表者関連者コード',
  `account_mgr_code` varchar(30) DEFAULT NULL COMMENT '会計責任者関連者個人コード',
  `account_mgr_name` varchar(30) DEFAULT NULL COMMENT '会計責任者関連者個人氏名',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_seijidantai_property_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
