CREATE TABLE `kanrensha_code_move` (
  `kanrensha_code_move_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kanrensha_code_move_code` int DEFAULT NULL COMMENT '関連者コード移動申請コード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新フラグ',
  `move_status` smallint DEFAULT NULL COMMENT '承認状態',
  `kanrensha_kbn` smallint DEFAULT NULL COMMENT '関連者区分',
  `origin_kanrensha_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '併合先コード',
  `origin_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '併合先コード名称',
  `abolish_kanrensha_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '廃止コード',
  `abolish_kanrensha_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '廃止コード名称',
  `move_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '移行理由',
  `is_abolish_last` tinyint DEFAULT NULL COMMENT '廃止コード最新該当',
  `task_year` int DEFAULT NULL COMMENT '発生年',
  `save_file_storage_id` int DEFAULT NULL COMMENT 'ストレージId',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_code_move_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
