CREATE TABLE `kanrensha_seijidantai_address` (
  `kanrensha_seijidantai_address_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kanrensha_seijidantai_id` int DEFAULT NULL COMMENT '関連者政治団体Id',
  `seijidantai_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者政治団体コード',
  `kanrensha_name` varchar(200) DEFAULT NULL COMMENT '関連者政治団体名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `postalcode1` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号1',
  `postalcode2` varchar(6) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号2',
  `address_postal` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住所郵便番号まで',
  `address_block` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住所番地',
  `address_building` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住所建物',
  `lg_code` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地方公共団体コード',
  `machiaza_id` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '町字Id',
  `blk_id` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '街区Id',
  `prc_id` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地番Id',
  `rsdt_id` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住居Id',
  `rsdt2_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住居2Id',
  `is_postal_edit` tinyint COMMENT '住所郵便番号まで編集有無',
  `is_block_edit` tinyint COMMENT '住所番地編集有無',
  `is_building_edit` tinyint COMMENT '住所建物編集有無',
  `is_postal_accept` tinyint DEFAULT NULL COMMENT '住所郵便番号承認該否',
  `is_block_accept` tinyint DEFAULT NULL COMMENT '住所番地承認該否',
  `is_building_accept` tinyint DEFAULT NULL COMMENT '住所建物承認該否',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(100) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(100) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_seijidantai_address_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
