CREATE TABLE `kanrensha_seijidantai_access` (
  `kanrensha_seijidantai_access_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `kanrensha_seijidantai_id` int DEFAULT NULL COMMENT '関連者政治団体Id',
  `seijidantai_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '関連者政治団体コード',
  `kanrensha_name` varchar(200) DEFAULT NULL COMMENT '関連者政治団体名',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `phon1` varchar(10) DEFAULT NULL COMMENT '電話番号1',
  `phon2` varchar(10) DEFAULT NULL COMMENT '電話番号2',
  `phon3` varchar(10) DEFAULT NULL COMMENT '電話番号3',
  `email` text COMMENT '電子メール',
  `my_portal_url` text COMMENT '代表(公式)サイトurl',
  `sns_service_id` int DEFAULT NULL COMMENT 'SNSサービスコード',
  `sns_service_code` int DEFAULT NULL COMMENT 'SNSサービスコード',
  `sns_service_name` text COMMENT 'SNSサービス名称',
  `sns_portal_url` text COMMENT 'SNS玄関url',
  `sns_account` text COMMENT 'SNSサービスアカウント',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_seijidantai_access_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
