CREATE TABLE `kanrensha_seijidantai_master` (
  `kanrensha_seijidantai_master_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `seijidantai_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '政治団体関連者コード',
  `poli_org_no` varchar(30) DEFAULT NULL COMMENT '政治団体番号',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `kanrensha_name` varchar(100) DEFAULT NULL COMMENT '企業・団体名',
  `all_address` varchar(100) DEFAULT NULL COMMENT '企業・団体全住所',
  `seijidantai_delegate` varchar(100) DEFAULT NULL COMMENT '企業・団体代表者',
  `dantai_kbn` varchar(2) DEFAULT NULL COMMENT '政治団体区分',
  `compare_name_text` varchar(100) DEFAULT NULL COMMENT '名称比較用',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`kanrensha_seijidantai_master_id`),
  FULLTEXT KEY `search_text_index` (`compare_name_text`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
