CREATE TABLE `task_plan_2025` (
  `task_plan_id` int NOT NULL AUTO_INCREMENT COMMENT 'タスク予定Id',
  `task_plan_code` int DEFAULT NULL COMMENT 'タスク予定コード',
  `task_info_code` int DEFAULT NULL COMMENT 'タスク設定コード',
  `task_plan_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'タスク予定名称',
  `table_year` int DEFAULT NULL,
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_start` tinyint DEFAULT NULL COMMENT '作業開始フラグ',
  `is_finished` tinyint DEFAULT NULL COMMENT '作業終了フラグ',
  `is_suspended` tinyint DEFAULT NULL COMMENT 'タスク中断フラグ',
  `start_datetime` datetime DEFAULT NULL COMMENT '開始日時',
  `end_dateimte` datetime DEFAULT NULL COMMENT '終了日時',
  `role_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '対象ユーザリスト',
  `transfer_pass` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '遷移パス',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`task_plan_id`),
  FULLTEXT KEY `name_index` (`task_plan_name`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB AUTO_INCREMENT=206 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
