CREATE TABLE `timer_yotei` (
  `timer_yotei_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `timer_yotei_code` int DEFAULT NULL COMMENT '予約実行コード',
  `timer_yotei_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '予約実行名称',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `yoyaku_task_kbn` smallint DEFAULT NULL COMMENT '予約作業区分',
  `next_timestamp` datetime DEFAULT NULL COMMENT '次回実行日時',
  `previous_timestamp` datetime DEFAULT NULL COMMENT '前回実行日時',
  `is_repeat` tinyint DEFAULT NULL COMMENT '繰り返し有無',
  `is_pause` tinyint DEFAULT NULL COMMENT '繰り返し中断',
  `end_timestamp` datetime DEFAULT NULL COMMENT 'タスク条件終了日時',
  `sabun_timestamp` datetime DEFAULT NULL COMMENT 'タスク条件差分日時',
  `is_period` tinyint DEFAULT NULL COMMENT '間隔指定該否',
  `year_period` smallint DEFAULT NULL COMMENT '間隔指定年条件',
  `month_period` smallint DEFAULT NULL COMMENT '間隔指定年条件',
  `day_period` smallint DEFAULT NULL COMMENT '間隔指定年条件',
  `hour_period` smallint DEFAULT NULL COMMENT '間隔指定年条件',
  `year_pointed` smallint DEFAULT NULL COMMENT '直接指定年条件',
  `month_pointed` smallint DEFAULT NULL COMMENT '直接指定年条件',
  `day_pointed` smallint DEFAULT NULL COMMENT '直接指定年条件',
  `hour_pointed` smallint DEFAULT NULL COMMENT '直接指定年条件',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`timer_yotei_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
