CREATE TABLE `wk_tbl_kanrensha_combine_org` (
  `wk_tbl_kanrensha_combine_org_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_tbl_kanrensha_combine_org_code` int DEFAULT NULL COMMENT '紐づけコード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_kbn` smallint DEFAULT NULL COMMENT '紐づけ関連者区分',
  `person_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '個人関連者コード',
  `person_name` varchar(30) DEFAULT NULL COMMENT '個人氏名',
  `org_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '団体関連者コード',
  `org_name` varchar(30) DEFAULT NULL COMMENT '団体代表者名称',
  `start_year` smallint DEFAULT NULL COMMENT '登録開始年',
  `end_year` smallint DEFAULT NULL COMMENT '登録終了年',
  `year_array_text` text COMMENT '登録年配列',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `judge_reason` varchar(300) DEFAULT NULL COMMENT '判定理由',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_kanrensha_combine_org_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
