CREATE TABLE `wk_tbl_postal_common` (
  `wk_tbl_postal_common_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `address_postal_id` int DEFAULT NULL COMMENT '正規テーブルId',
  `address_postal_irregular_id` int DEFAULT NULL COMMENT '不規則Id',
  `address_postal_repair_log_id` int DEFAULT NULL COMMENT '修正ログId',
  `postalcode1` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号1',
  `postalcode2` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号2',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `lg_code` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地方自治体コード',
  `address_org` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原文書住所',
  `address_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '住所郵便番号まで',
  `is_gyoseiku_data` tinyint DEFAULT NULL COMMENT '行政区データ該否',
  `address_postal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '住所郵便番号まで',
  `address_block` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '住所番地まで',
  `is_add_postal` tinyint DEFAULT NULL COMMENT '郵便番号テーブル追加',
  `is_repair_rsdt` tinyint DEFAULT NULL COMMENT '住居テーブル修正可否',
  `status_text` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '状態表示',
  `is_confirm` tinyint DEFAULT NULL COMMENT '修正承認有無',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_postal_common_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
