CREATE TABLE `wk_tbl_kanrensha_person_history` (
  `wk_kanrensha_person_history_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_kanrensha_person_history_code` int DEFAULT NULL COMMENT '関連者企業・団体コード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_name` varchar(100) DEFAULT NULL COMMENT '企業・団体名',
  `all_address` varchar(100) DEFAULT NULL COMMENT '企業・団体全住所',
  `person_shokugyou` varchar(100) DEFAULT NULL COMMENT '企業・団体代表者',
  `person_kanrensha_code` varchar(30) DEFAULT NULL COMMENT '企業・団体関連者コード',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `judge_reason` varchar(300) DEFAULT NULL COMMENT '判定理由',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_kanrensha_person_history_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
