CREATE TABLE `wk_tbl_kanrensha_kigyou_dt_master` (
  `wk_tbl_kanrensha_kigyou_dt_master_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_tbl_kanrensha_kigyou_dt_master_code` int DEFAULT NULL COMMENT 'ワークテーブルコード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '企業・団体名',
  `all_address` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '企業・団体全住所',
  `kigyou_dt_delegate` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '企業・団体代表者',
  `houjin_no` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '法人番号',
  `org_name_kana` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '関連者団体名称かな',
  `is_shiten` tinyint DEFAULT NULL COMMENT '支店該当',
  `org_delegate_code` varchar(30) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '団体代表者関連者コード',
  `address_postal` text COLLATE utf8mb4_bin COMMENT '住所郵便番号',
  `address_block` text COLLATE utf8mb4_bin COMMENT '住所番地',
  `address_building` text COLLATE utf8mb4_bin COMMENT '住所建物',
  `postalcode1` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号1',
  `postalcode2` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号2',
  `lg_code` varchar(8) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地方自治体コード',
  `machiaza_id` varchar(9) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '町字コード',
  `blk_id` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '街区コード',
  `prc_id` varchar(17) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地番コード',
  `rsdt_id` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住居コード',
  `rsdt2_id` varchar(7) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '住居2コード',
  `phon1` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '電話番号1',
  `phon2` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '電話番号2',
  `phon3` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '電話番号3',
  `email` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '電子メール',
  `my_portal_url` text COLLATE utf8mb4_bin COMMENT '代表(公式)サイトurl',
  `sns_service_name` text COLLATE utf8mb4_bin COMMENT 'SNSサービス名称',
  `sns_account` text COLLATE utf8mb4_bin COMMENT 'SNSサービスアカウント',
  `houjin_sbts` varchar(5) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '法人種別',
  `is_foreign` tinyint DEFAULT NULL COMMENT '外国籍該否',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `judge_reason` varchar(300) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '判定理由',
  `is_jhusho_format` tinyint DEFAULT NULL COMMENT '住所整形済',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_kanrensha_kigyou_dt_master_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
