CREATE TABLE `wk_tbl_postal_edit` (
  `wk_tbl_postal_edit_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `flg_edit` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '編集フラグ',
  `is_repair` tinyint DEFAULT NULL COMMENT '修正可否',
  `lg_code` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地方自治体コード',
  `postalcode5` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号5桁',
  `postalcode7` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '郵便番号7桁',
  `pref_name_kana` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '県名カナ',
  `city_name_kana` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '市区町名カナ',
  `org_name_kana` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原文書名カナ',
  `pref_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '県名',
  `city_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '市区町名',
  `org_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '原文書名',
  `flg_prop1` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '属性1フラグ',
  `flg_prop2` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '属性2フラグ',
  `flg_prop3` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '属性3フラグ',
  `flg_prop4` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '属性4フラグ',
  `flg_koushin` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新表示フラグ',
  `flg_henkou_riyu` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '変更理由フラグ',
  `address_postal_id` int DEFAULT NULL COMMENT '正規テーブルId',
  `is_gyoseiku_data` tinyint DEFAULT NULL COMMENT '行政区データ該否',
  `address_postal_irregular_id` int DEFAULT NULL COMMENT '不規則Id',
  `works_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '編集内容説明',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_postal_edit_id`)
) ENGINE=InnoDB AUTO_INCREMENT=628 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin