CREATE TABLE `wk_tbl_kanrensha_seijidantai_master` (
  `wk_tbl_kanrensha_seijidantai_master_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_tbl_kanrensha_seijidantai_master_code` int DEFAULT NULL COMMENT 'ワークテーブルコード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_name` varchar(100) DEFAULT NULL COMMENT '政治団体名',
  `all_address` varchar(100) DEFAULT NULL COMMENT '政治団体全住所',
  `seijidantai_delegate` varchar(100) DEFAULT NULL COMMENT '政治団体代表者',
  `dantai_kbn` varchar(2) DEFAULT NULL COMMENT '政治団体区分',
  `poli_org_no` varchar(30) DEFAULT NULL COMMENT '政治団体番号',
  `address_postal` text COMMENT '住所郵便番号',
  `address_block` text COMMENT '住所番地',
  `address_building` text COMMENT '住所建物',
  `postal1` varchar(8) DEFAULT NULL COMMENT '郵便番号1',
  `postal2` varchar(8) DEFAULT NULL COMMENT '郵便番号2',
  `lg_code` varchar(8) DEFAULT NULL COMMENT '地方自治体コード',
  `machiaza_id` varchar(9) DEFAULT NULL COMMENT '町字コード',
  `blk_id` varchar(5) DEFAULT NULL COMMENT '街区コード',
  `rsdt_id` varchar(5) DEFAULT NULL COMMENT '住居コード',
  `rsdt2_id` varchar(7) DEFAULT NULL COMMENT '住居2コード',
  `phon1` varchar(10) DEFAULT NULL COMMENT '電話番号1',
  `phon2` varchar(10) DEFAULT NULL COMMENT '電話番号2',
  `phon3` varchar(10) DEFAULT NULL COMMENT '電話番号3',
  `email` text COMMENT '電子メール',
  `my_portal_url` text,
  `sns_service_name` text COMMENT 'SNSサービス名称',
  `sns_account` text COMMENT 'SNSサービスアカウント',
  `org_name_kana` varchar(200) DEFAULT NULL COMMENT '関連者団体名称かな',
  `org_delegate_code` varchar(30) DEFAULT NULL COMMENT '団体代表者関連者コード',
  `account_mgr_code` varchar(30) DEFAULT NULL COMMENT '会計責任者関連者個人コード',
  `account_mgr_name` varchar(200) DEFAULT NULL COMMENT '会計責任者関連者個人氏名',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `judge_reason` varchar(300) DEFAULT NULL COMMENT '判定理由',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_kanrensha_seijidantai_master_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
