CREATE TABLE `wk_tbl_master_all_by_xml` (
  `wk_tbl_master_all_by_xml_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_tbl_master_all_by_xml_code` int DEFAULT NULL COMMENT '紐づけコード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_kbn` smallint DEFAULT NULL COMMENT '関連者区分',
  `bikou` text COMMENT '備考',
  `kanrensha_name` varchar(300) DEFAULT NULL COMMENT '関連者名称',
  `all_address` varchar(300) DEFAULT NULL COMMENT '全住所',
  `org_delegate` varchar(300) DEFAULT NULL COMMENT '団体代表者',
  `person_shokugyou` varchar(300) DEFAULT NULL COMMENT '個人職業',
  `houjin_no` varchar(15) DEFAULT NULL COMMENT '法人番号',
  `dantai_kbn` varchar(5) DEFAULT NULL COMMENT '団体区分',
  `youshiki_kbn` smallint DEFAULT NULL COMMENT '様式区分',
  `youshiki_eda_kbn` smallint DEFAULT NULL COMMENT '様式枝区分項目',
  `input_src_name` varchar(300) DEFAULT NULL COMMENT '複写元名称',
  `input_src_address` text COMMENT '複写元住所',
  `input_src_key` varchar(300) DEFAULT NULL COMMENT '複写元認識キー',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `is_disabled` tinyint DEFAULT NULL COMMENT '編集対象該否',
  `judge_reason` varchar(300) DEFAULT NULL COMMENT '判定理由',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_master_all_by_xml_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
