CREATE TABLE `wk_tbl_kanrensha_person_master` (
  `wk_tbl_kanrensha_person_master_id` int NOT NULL AUTO_INCREMENT COMMENT 'テーブルId',
  `wk_tbl_kanrensha_person_master_code` int DEFAULT NULL COMMENT 'ワークテーブルコード',
  `is_latest` tinyint DEFAULT NULL COMMENT '最新該否',
  `is_finish` tinyint DEFAULT NULL COMMENT '処理完了該否',
  `kanrensha_name` varchar(100) DEFAULT NULL COMMENT '個人名',
  `all_address` varchar(100) DEFAULT NULL COMMENT '個人全住所',
  `person_shokugyou` varchar(100) DEFAULT NULL COMMENT '個人職業',
  `address_postal` text COMMENT '住所郵便番号',
  `address_block` text COMMENT '住所番地',
  `address_building` text COMMENT '住所建物',
  `postal1` varchar(8) DEFAULT NULL COMMENT '郵便番号1',
  `postal2` varchar(8) DEFAULT NULL COMMENT '郵便番号2',
  `lg_code` varchar(8) DEFAULT NULL COMMENT '地方自治体コード',
  `machiaza_id` varchar(9) DEFAULT NULL COMMENT '町字コード',
  `blk_id` varchar(5) DEFAULT NULL COMMENT '街区コード',
  `rsdt_id` varchar(5) DEFAULT NULL COMMENT '住居コード',
  `rsdt2_id` varchar(7) DEFAULT NULL COMMENT '住居2コード',
  `phon1` varchar(10) DEFAULT NULL COMMENT '電話番号1',
  `phon2` varchar(10) DEFAULT NULL COMMENT '電話番号2',
  `phon3` varchar(10) DEFAULT NULL COMMENT '電話番号3',
  `email` text COMMENT '電子メール',
  `my_portal_url` text COMMENT '代表(公式)url',
  `sns_service_name` text COMMENT 'SNSサービス名称',
  `sns_account` text COMMENT 'SNSサービスアカウント',
  `last_name` varchar(100) DEFAULT NULL COMMENT '姓名の姓',
  `first_name` varchar(100) DEFAULT NULL COMMENT '姓名の名',
  `middle_name` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネーム',
  `last_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の姓かな',
  `first_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名の名かな',
  `middle_name_kana` varchar(100) DEFAULT NULL COMMENT '姓名のミドルネームかな',
  `gyoushu` varchar(100) DEFAULT NULL COMMENT '職業の業種',
  `yakushoku` varchar(100) DEFAULT NULL COMMENT '職業の役職',
  `shokugyou_user_write` varchar(100) DEFAULT NULL COMMENT 'ユーザ記述の職業',
  `kigyou_dt_no` varchar(100) DEFAULT NULL COMMENT '企業番号',
  `kigyou_dt_address` varchar(100) DEFAULT NULL COMMENT '企業所在地',
  `kigyou_dt_name` varchar(100) DEFAULT NULL COMMENT '企業名',
  `is_foreign` tinyint DEFAULT NULL COMMENT '外国籍該否',
  `is_affected` tinyint DEFAULT NULL COMMENT '反映有無',
  `judge_reason` varchar(300) DEFAULT NULL COMMENT '判定理由',
  `insert_user_id` int DEFAULT NULL COMMENT '挿入ユーザId',
  `insert_user_code` int DEFAULT NULL COMMENT '挿入ユーザコード',
  `insert_user_name` varchar(200) DEFAULT NULL COMMENT '挿入ユーザ名称',
  `insert_timestamp` datetime DEFAULT NULL COMMENT '挿入日時',
  `delete_user_id` int DEFAULT NULL COMMENT '無効ユーザId',
  `delete_user_code` int DEFAULT NULL COMMENT '無効ユーザコード',
  `delete_user_name` varchar(200) DEFAULT NULL COMMENT '無効ユーザ名称',
  `delete_timestamp` datetime DEFAULT NULL COMMENT '無効日時',
  PRIMARY KEY (`wk_tbl_kanrensha_person_master_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
