SET foreign_key_checks = 0; 
TRUNCATE TABLE BATCH_JOB_INSTANCE;
TRUNCATE TABLE BATCH_JOB_EXECUTION;
TRUNCATE TABLE BATCH_JOB_EXECUTION_PARAMS;
TRUNCATE TABLE BATCH_JOB_EXECUTION_CONTEXT;
TRUNCATE TABLE BATCH_STEP_EXECUTION ;
TRUNCATE TABLE BATCH_STEP_EXECUTION ;
TRUNCATE TABLE BATCH_STEP_EXECUTION_CONTEXT ;

TRUNCATE TABLE BATCH_STEP_EXECUTION_SEQ ;
TRUNCATE TABLE BATCH_JOB_EXECUTION_SEQ ;
TRUNCATE TABLE BATCH_JOB_SEQ ;

SET foreign_key_checks = 1;

INSERT INTO BATCH_STEP_EXECUTION_SEQ values(0);
INSERT INTO BATCH_JOB_EXECUTION_SEQ values(0);
INSERT INTO BATCH_JOB_SEQ values(0);
