server {
    listen 80;
    server_name localhost;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    #  ここに /dump/ 用の配信設定を追加
    location /dump/ {
        alias /usr/share/nginx/html/store_storage/kanrensha-v02/front_data/public/dump/;
        autoindex on;
    }

    # Serve files for SPA with base path /
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        # HTMLファイル（index.html）のみ、ブラウザに一切キャッシュさせない設定
        if ($request_filename ~* .*(?:htm|html)$) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }
    }

    # Error handling
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
