DELETE FROM `wk_tbl_master_all_by_xml`;
ALTER TABLE `wk_tbl_master_all_by_xml` auto_increment = 0;

INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (1,1,1,0,0,'備考','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',8,3,'名称A','事務所住所B','職業または団体代表者C',0,0,'別テ)',253,232,'ユーザ','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');

INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (124,124,1,0,0,'ネット工作会社A','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (125,125,1,0,0,'ネット工作会社B','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (126,126,1,0,0,'ネット工作会社C','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (127,127,1,0,0,'ネット工作会社D','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (128,128,1,0,0,'選挙工作会社1','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (129,129,1,0,0,'選挙工作会社2','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');

INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (140,140,1,0,0,'ネット工作会社A','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',4,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (141,141,1,0,0,'ネット工作会社A','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',6,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (142,142,1,0,0,'選挙工作会社1','名称A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',3,0,'名称A','事務所住所B','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');


INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (231,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',14,2,'購入先A','事務所住所1','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (232,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',14,2,'購入先B','事務所住所2','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (233,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',14,2,'購入先A','事務所住所3','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (234,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',14,2,'購入先B','事務所住所4','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (235,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',14,2,'購入先C','事務所住所5','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');

INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (240,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',15,6,'購入先A','事務所住所1','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (241,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',5,0,'購入先A','事務所住所1','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (242,124,1,0,0,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','団体区分',16,0,'購入先B','事務所住所2','職業または団体代表者C',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');


INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (311,311,1,0,1,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',7,1,'購入先A','事務所住所1','職業または団体代表者C1',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (312,312,1,0,2,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',8,2,'購入先B','事務所住所2','職業または団体代表者C2',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (313,313,1,0,3,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',11,3,'購入先A','事務所住所3','職業または団体代表者C3',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (314,314,1,0,2,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',12,2,'購入先B','事務所住所4','職業または団体代表者C4',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (315,316,1,0,1,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',7,1,'購入先C','事務所住所5','職業または団体代表者C5',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');

INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (340,311,1,0,2,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',11,2,'購入先A','事務所住所1','職業または団体代表者C1',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (341,311,1,0,3,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',8,3,'購入先A','事務所住所1','職業または団体代表者C1',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_master_all_by_xml` (`wk_tbl_master_all_by_xml_id`,`wk_tbl_master_all_by_xml_code`,`is_latest`,`is_finish`,`kanrensha_kbn`,`bikou`,`kanrensha_name`,`all_address`,`org_delegate`,`person_shokugyou`,`houjin_no`,`dantai_kbn`,`youshiki_kbn`,`youshiki_eda_kbn`,`input_src_name`,`input_src_address`,`input_src_key`,`is_affected`,`is_disabled`,`judge_reason`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (342,312,1,0,1,'備考','購入先A','事務所住所B','職業または団体代表者C','職業または団体代表者C','法人番号','01',12,1,'購入先B','事務所住所2','職業または団体代表者C2',0,0,'関連者区分が指定されていません;',196,190,'管理人　太郎','2022-12-05 12:34:56',0,0,'','1948-07-28 23:00:00');

