DELETE FROM `kanrensha_person_master`;
ALTER TABLE `kanrensha_person_master` auto_increment = 0;

DELETE FROM `kanrensha_person_access`;
ALTER TABLE `kanrensha_person_access` auto_increment = 0;

DELETE FROM `kanrensha_person_history_01`;
DELETE FROM `kanrensha_person_history_02`;
DELETE FROM `kanrensha_person_history_03`;
DELETE FROM `kanrensha_person_history_04`;
DELETE FROM `kanrensha_person_history_05`;
DELETE FROM `kanrensha_person_history_06`;
DELETE FROM `kanrensha_person_history_07`;
DELETE FROM `kanrensha_person_history_08`;
DELETE FROM `kanrensha_person_history_09`;
DELETE FROM `kanrensha_person_history_10`;
DELETE FROM `kanrensha_person_history_11`;
DELETE FROM `kanrensha_person_history_12`;
DELETE FROM `kanrensha_person_history_13`;
DELETE FROM `kanrensha_person_history_14`;
DELETE FROM `kanrensha_person_history_15`;
DELETE FROM `kanrensha_person_history_16`;
DELETE FROM `kanrensha_person_history_17`;
DELETE FROM `kanrensha_person_history_18`;
DELETE FROM `kanrensha_person_history_19`;
DELETE FROM `kanrensha_person_history_20`;
DELETE FROM `kanrensha_person_history_21`;
DELETE FROM `kanrensha_person_history_22`;
DELETE FROM `kanrensha_person_history_23`;
DELETE FROM `kanrensha_person_history_24`;
DELETE FROM `kanrensha_person_history_25`;
DELETE FROM `kanrensha_person_history_26`;
DELETE FROM `kanrensha_person_history_27`;
DELETE FROM `kanrensha_person_history_28`;
DELETE FROM `kanrensha_person_history_29`;
DELETE FROM `kanrensha_person_history_30`;
DELETE FROM `kanrensha_person_history_31`;
DELETE FROM `kanrensha_person_history_32`;
DELETE FROM `kanrensha_person_history_33`;
DELETE FROM `kanrensha_person_history_34`;
DELETE FROM `kanrensha_person_history_35`;
DELETE FROM `kanrensha_person_history_36`;
DELETE FROM `kanrensha_person_history_37`;
DELETE FROM `kanrensha_person_history_38`;
DELETE FROM `kanrensha_person_history_39`;
DELETE FROM `kanrensha_person_history_40`;
DELETE FROM `kanrensha_person_history_41`;
DELETE FROM `kanrensha_person_history_42`;
DELETE FROM `kanrensha_person_history_43`;
DELETE FROM `kanrensha_person_history_44`;
DELETE FROM `kanrensha_person_history_45`;
DELETE FROM `kanrensha_person_history_46`;
DELETE FROM `kanrensha_person_history_47`;
DELETE FROM `kanrensha_person_history_99`;

ALTER TABLE `kanrensha_person_history_01` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_02` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_03` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_04` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_05` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_06` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_07` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_08` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_09` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_10` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_11` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_12` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_13` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_14` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_15` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_16` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_17` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_18` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_19` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_20` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_21` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_22` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_23` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_24` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_25` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_26` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_27` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_28` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_29` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_30` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_31` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_32` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_33` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_34` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_35` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_36` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_37` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_38` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_39` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_40` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_41` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_42` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_43` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_44` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_45` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_46` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_47` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_99` auto_increment = 0;


DELETE FROM `wk_tbl_kanrensha_person_master`;
ALTER TABLE `wk_tbl_kanrensha_person_master` auto_increment = 0;


INSERT INTO `wk_tbl_kanrensha_person_master` (`wk_tbl_kanrensha_person_master_id`,`wk_tbl_kanrensha_person_master_code`,`is_latest`,`is_finish`,`kanrensha_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postalcode1`,`postalcode2`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_name`,`sns_account`,`last_name`,`first_name`,`middle_name`,`last_name_kana`,`first_name_kana`,`middle_name_kana`,`gyoushu`,`yakushoku`,`shokugyou_user_write`,`kigyou_dt_no`,`kigyou_dt_address`,`kigyou_dt_name`,`is_foreign`,`is_affected`,`judge_reason`,`is_jusho_format`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (296,296,1,0,'団体名','全住所','職業','郵便番号住所','番地住所','建物住所','987','6543','012','123','234','345','678','567','8901','2345','aaa@bbbb.net','https://bbb.net/','弱小ブログ','@abcds','迂回献金','太郎','ミカエル','太郎','たろう','みかえる','水産業','団体役員','正義の味方','1-2345','和歌山県実在市山麓町','超元素製造組合',1,1,'理由',0,219,190,'代表者　太郎','2025-07-19 19:30:57',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_kanrensha_person_master` (`wk_tbl_kanrensha_person_master_id`,`wk_tbl_kanrensha_person_master_code`,`is_latest`,`is_finish`,`kanrensha_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postalcode1`,`postalcode2`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_name`,`sns_account`,`last_name`,`first_name`,`middle_name`,`last_name_kana`,`first_name_kana`,`middle_name_kana`,`gyoushu`,`yakushoku`,`shokugyou_user_write`,`kigyou_dt_no`,`kigyou_dt_address`,`kigyou_dt_name`,`is_foreign`,`is_affected`,`judge_reason`,`is_jusho_format`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (297,296,0,0,'団体名','全住所','職業','郵便番号住所','番地住所','建物住所','987','6543','012','123','234','345','678','567','8901','2345','aaa@bbbb.net','https://bbb.net/','弱小ブログ','@abcds','迂回献金','太郎','ミカエル','太郎','たろう','みかえる','水産業','団体役員','正義の味方','1-2345','和歌山県実在市山麓町','超元素製造組合',1,1,'理由',0,219,190,'代表者　太郎','2025-07-19 19:30:57',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_kanrensha_person_master` (`wk_tbl_kanrensha_person_master_id`,`wk_tbl_kanrensha_person_master_code`,`is_latest`,`is_finish`,`kanrensha_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postalcode1`,`postalcode2`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_name`,`sns_account`,`last_name`,`first_name`,`middle_name`,`last_name_kana`,`first_name_kana`,`middle_name_kana`,`gyoushu`,`yakushoku`,`shokugyou_user_write`,`kigyou_dt_no`,`kigyou_dt_address`,`kigyou_dt_name`,`is_foreign`,`is_affected`,`judge_reason`,`is_jusho_format`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (298,296,1,0,'団体名','全住所','職業','郵便番号住所','番地住所','建物住所','987','6543','012','123','234','345','678','567','8901','2345','aaa@bbbb.net','https://bbb.net/','弱小ブログ','@abcds','迂回献金','太郎','ミカエル','太郎','たろう','みかえる','水産業','団体役員','正義の味方','1-2345','和歌山県実在市山麓町','超元素製造組合',1,0,'理由',0,219,190,'代表者　太郎','2025-07-19 19:30:57',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_kanrensha_person_master` (`wk_tbl_kanrensha_person_master_id`,`wk_tbl_kanrensha_person_master_code`,`is_latest`,`is_finish`,`kanrensha_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postalcode1`,`postalcode2`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_name`,`sns_account`,`last_name`,`first_name`,`middle_name`,`last_name_kana`,`first_name_kana`,`middle_name_kana`,`gyoushu`,`yakushoku`,`shokugyou_user_write`,`kigyou_dt_no`,`kigyou_dt_address`,`kigyou_dt_name`,`is_foreign`,`is_affected`,`judge_reason`,`is_jusho_format`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (299,296,1,1,'団体名','全住所','職業','郵便番号住所','番地住所','建物住所','987','6543','012','123','234','345','678','567','8901','2345','aaa@bbbb.net','https://bbb.net/','弱小ブログ','@abcds','迂回献金','太郎','ミカエル','太郎','たろう','みかえる','水産業','団体役員','正義の味方','1-2345','和歌山県実在市山麓町','超元素製造組合',1,0,'理由',0,219,190,'代表者　太郎','2025-07-19 19:30:57',0,0,'','1948-07-28 23:00:00');
INSERT INTO `wk_tbl_kanrensha_person_master` (`wk_tbl_kanrensha_person_master_id`,`wk_tbl_kanrensha_person_master_code`,`is_latest`,`is_finish`,`kanrensha_name`,`all_address`,`person_shokugyou`,`address_postal`,`address_block`,`address_building`,`postalcode1`,`postalcode2`,`lg_code`,`machiaza_id`,`blk_id`,`rsdt_id`,`rsdt2_id`,`phon1`,`phon2`,`phon3`,`email`,`my_portal_url`,`sns_service_name`,`sns_account`,`last_name`,`first_name`,`middle_name`,`last_name_kana`,`first_name_kana`,`middle_name_kana`,`gyoushu`,`yakushoku`,`shokugyou_user_write`,`kigyou_dt_no`,`kigyou_dt_address`,`kigyou_dt_name`,`is_foreign`,`is_affected`,`judge_reason`,`is_jusho_format`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) VALUES (300,296,1,0,'団体名','全住所','職業','郵便番号住所','番地住所','建物住所','987','6543','012','123','234','345','678','567','8901','2345','aaa@bbbb.net','https://bbb.net/','弱小ブログ','@abcds','迂回献金','太郎','ミカエル','太郎','たろう','みかえる','水産業','団体役員','正義の味方','1-2345','和歌山県実在市山麓町','超元素製造組合',1,1,'理由',0,253,237,'代表者　太郎','2025-07-19 19:30:57',0,0,'','1948-07-28 23:00:00');
