DELETE FROM `timer_yotei`;
ALTER TABLE `timer_yotei` auto_increment = 0;

INSERT INTO `timer_yotei` (`timer_yotei_id`,`timer_yotei_code`,`timer_yotei_name`,`is_latest`,`yoyaku_task_kbn`,`next_timestamp`,`previous_timestamp`,`is_repeat`,`is_pause`,`end_timestamp`,`sabun_timestamp`,`is_period`,`year_period`,`month_period`,`day_period`,`hour_period`,`year_pointed`,`month_pointed`,`day_pointed`,`hour_pointed`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) 
  VALUES 
    (123,116,'サンプルタスク',1,101,'1990-06-11 12:34:56','1989-12-05 12:34:56',1,0,'2023-01-01 00:00:00','2022-07-01 00:00:00',1,2,7,4,9,2026,10,28,1,213,190,'ユーザ','2022-12-05 00:00:00',0,0,NULL,'1947-07-28 23:59:59')
;

-- 企業団体履歴
DELETE FROM `kanrensha_kigyou_dt_history_01`;
DELETE FROM `kanrensha_kigyou_dt_history_02`;
DELETE FROM `kanrensha_kigyou_dt_history_03`;
DELETE FROM `kanrensha_kigyou_dt_history_04`;
DELETE FROM `kanrensha_kigyou_dt_history_05`;
DELETE FROM `kanrensha_kigyou_dt_history_06`;
DELETE FROM `kanrensha_kigyou_dt_history_07`;
DELETE FROM `kanrensha_kigyou_dt_history_08`;
DELETE FROM `kanrensha_kigyou_dt_history_09`;
DELETE FROM `kanrensha_kigyou_dt_history_10`;
DELETE FROM `kanrensha_kigyou_dt_history_11`;
DELETE FROM `kanrensha_kigyou_dt_history_12`;
DELETE FROM `kanrensha_kigyou_dt_history_13`;
DELETE FROM `kanrensha_kigyou_dt_history_14`;
DELETE FROM `kanrensha_kigyou_dt_history_15`;
DELETE FROM `kanrensha_kigyou_dt_history_16`;
DELETE FROM `kanrensha_kigyou_dt_history_17`;
DELETE FROM `kanrensha_kigyou_dt_history_18`;
DELETE FROM `kanrensha_kigyou_dt_history_19`;
DELETE FROM `kanrensha_kigyou_dt_history_20`;
DELETE FROM `kanrensha_kigyou_dt_history_21`;
DELETE FROM `kanrensha_kigyou_dt_history_22`;
DELETE FROM `kanrensha_kigyou_dt_history_23`;
DELETE FROM `kanrensha_kigyou_dt_history_24`;
DELETE FROM `kanrensha_kigyou_dt_history_25`;
DELETE FROM `kanrensha_kigyou_dt_history_26`;
DELETE FROM `kanrensha_kigyou_dt_history_27`;
DELETE FROM `kanrensha_kigyou_dt_history_28`;
DELETE FROM `kanrensha_kigyou_dt_history_29`;
DELETE FROM `kanrensha_kigyou_dt_history_30`;
DELETE FROM `kanrensha_kigyou_dt_history_31`;
DELETE FROM `kanrensha_kigyou_dt_history_32`;
DELETE FROM `kanrensha_kigyou_dt_history_33`;
DELETE FROM `kanrensha_kigyou_dt_history_34`;
DELETE FROM `kanrensha_kigyou_dt_history_35`;
DELETE FROM `kanrensha_kigyou_dt_history_36`;
DELETE FROM `kanrensha_kigyou_dt_history_37`;
DELETE FROM `kanrensha_kigyou_dt_history_38`;
DELETE FROM `kanrensha_kigyou_dt_history_39`;
DELETE FROM `kanrensha_kigyou_dt_history_40`;
DELETE FROM `kanrensha_kigyou_dt_history_41`;
DELETE FROM `kanrensha_kigyou_dt_history_42`;
DELETE FROM `kanrensha_kigyou_dt_history_43`;
DELETE FROM `kanrensha_kigyou_dt_history_44`;
DELETE FROM `kanrensha_kigyou_dt_history_45`;
DELETE FROM `kanrensha_kigyou_dt_history_46`;
DELETE FROM `kanrensha_kigyou_dt_history_47`;
DELETE FROM `kanrensha_kigyou_dt_history_99`;

ALTER TABLE `kanrensha_kigyou_dt_history_01` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_02` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_03` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_04` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_05` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_06` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_07` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_08` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_09` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_10` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_11` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_12` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_13` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_14` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_15` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_16` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_17` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_18` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_19` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_20` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_21` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_22` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_23` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_24` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_25` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_26` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_27` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_28` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_29` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_30` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_31` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_32` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_33` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_34` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_35` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_36` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_37` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_38` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_39` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_40` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_41` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_42` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_43` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_44` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_45` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_46` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_47` auto_increment = 0;
ALTER TABLE `kanrensha_kigyou_dt_history_99` auto_increment = 0;

DELETE FROM `kanrensha_person_history_01`;
DELETE FROM `kanrensha_person_history_02`;
DELETE FROM `kanrensha_person_history_03`;
DELETE FROM `kanrensha_person_history_04`;
DELETE FROM `kanrensha_person_history_05`;
DELETE FROM `kanrensha_person_history_06`;
DELETE FROM `kanrensha_person_history_07`;
DELETE FROM `kanrensha_person_history_08`;
DELETE FROM `kanrensha_person_history_09`;
DELETE FROM `kanrensha_person_history_10`;
DELETE FROM `kanrensha_person_history_11`;
DELETE FROM `kanrensha_person_history_12`;
DELETE FROM `kanrensha_person_history_13`;
DELETE FROM `kanrensha_person_history_14`;
DELETE FROM `kanrensha_person_history_15`;
DELETE FROM `kanrensha_person_history_16`;
DELETE FROM `kanrensha_person_history_17`;
DELETE FROM `kanrensha_person_history_18`;
DELETE FROM `kanrensha_person_history_19`;
DELETE FROM `kanrensha_person_history_20`;
DELETE FROM `kanrensha_person_history_21`;
DELETE FROM `kanrensha_person_history_22`;
DELETE FROM `kanrensha_person_history_23`;
DELETE FROM `kanrensha_person_history_24`;
DELETE FROM `kanrensha_person_history_25`;
DELETE FROM `kanrensha_person_history_26`;
DELETE FROM `kanrensha_person_history_27`;
DELETE FROM `kanrensha_person_history_28`;
DELETE FROM `kanrensha_person_history_29`;
DELETE FROM `kanrensha_person_history_30`;
DELETE FROM `kanrensha_person_history_31`;
DELETE FROM `kanrensha_person_history_32`;
DELETE FROM `kanrensha_person_history_33`;
DELETE FROM `kanrensha_person_history_34`;
DELETE FROM `kanrensha_person_history_35`;
DELETE FROM `kanrensha_person_history_36`;
DELETE FROM `kanrensha_person_history_37`;
DELETE FROM `kanrensha_person_history_38`;
DELETE FROM `kanrensha_person_history_39`;
DELETE FROM `kanrensha_person_history_40`;
DELETE FROM `kanrensha_person_history_41`;
DELETE FROM `kanrensha_person_history_42`;
DELETE FROM `kanrensha_person_history_43`;
DELETE FROM `kanrensha_person_history_44`;
DELETE FROM `kanrensha_person_history_45`;
DELETE FROM `kanrensha_person_history_46`;
DELETE FROM `kanrensha_person_history_47`;
DELETE FROM `kanrensha_person_history_99`;

ALTER TABLE `kanrensha_person_history_01` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_02` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_03` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_04` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_05` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_06` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_07` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_08` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_09` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_10` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_11` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_12` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_13` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_14` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_15` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_16` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_17` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_18` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_19` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_20` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_21` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_22` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_23` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_24` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_25` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_26` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_27` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_28` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_29` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_30` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_31` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_32` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_33` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_34` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_35` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_36` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_37` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_38` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_39` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_40` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_41` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_42` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_43` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_44` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_45` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_46` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_47` auto_increment = 0;
ALTER TABLE `kanrensha_person_history_99` auto_increment = 0;

 
DELETE FROM `kanrensha_seijidantai_history_01`;
DELETE FROM `kanrensha_seijidantai_history_02`;
DELETE FROM `kanrensha_seijidantai_history_03`;
DELETE FROM `kanrensha_seijidantai_history_04`;
DELETE FROM `kanrensha_seijidantai_history_05`;
DELETE FROM `kanrensha_seijidantai_history_06`;
DELETE FROM `kanrensha_seijidantai_history_07`;
DELETE FROM `kanrensha_seijidantai_history_08`;
DELETE FROM `kanrensha_seijidantai_history_09`;
DELETE FROM `kanrensha_seijidantai_history_10`;
DELETE FROM `kanrensha_seijidantai_history_11`;
DELETE FROM `kanrensha_seijidantai_history_12`;
DELETE FROM `kanrensha_seijidantai_history_13`;
DELETE FROM `kanrensha_seijidantai_history_14`;
DELETE FROM `kanrensha_seijidantai_history_15`;
DELETE FROM `kanrensha_seijidantai_history_16`;
DELETE FROM `kanrensha_seijidantai_history_17`;
DELETE FROM `kanrensha_seijidantai_history_18`;
DELETE FROM `kanrensha_seijidantai_history_19`;
DELETE FROM `kanrensha_seijidantai_history_20`;
DELETE FROM `kanrensha_seijidantai_history_21`;
DELETE FROM `kanrensha_seijidantai_history_22`;
DELETE FROM `kanrensha_seijidantai_history_23`;
DELETE FROM `kanrensha_seijidantai_history_24`;
DELETE FROM `kanrensha_seijidantai_history_25`;
DELETE FROM `kanrensha_seijidantai_history_26`;
DELETE FROM `kanrensha_seijidantai_history_27`;
DELETE FROM `kanrensha_seijidantai_history_28`;
DELETE FROM `kanrensha_seijidantai_history_29`;
DELETE FROM `kanrensha_seijidantai_history_30`;
DELETE FROM `kanrensha_seijidantai_history_31`;
DELETE FROM `kanrensha_seijidantai_history_32`;
DELETE FROM `kanrensha_seijidantai_history_33`;
DELETE FROM `kanrensha_seijidantai_history_34`;
DELETE FROM `kanrensha_seijidantai_history_35`;
DELETE FROM `kanrensha_seijidantai_history_36`;
DELETE FROM `kanrensha_seijidantai_history_37`;
DELETE FROM `kanrensha_seijidantai_history_38`;
DELETE FROM `kanrensha_seijidantai_history_39`;
DELETE FROM `kanrensha_seijidantai_history_40`;
DELETE FROM `kanrensha_seijidantai_history_41`;
DELETE FROM `kanrensha_seijidantai_history_42`;
DELETE FROM `kanrensha_seijidantai_history_43`;
DELETE FROM `kanrensha_seijidantai_history_44`;
DELETE FROM `kanrensha_seijidantai_history_45`;
DELETE FROM `kanrensha_seijidantai_history_46`;
DELETE FROM `kanrensha_seijidantai_history_47`;
DELETE FROM `kanrensha_seijidantai_history_99`;

ALTER TABLE `kanrensha_seijidantai_history_01` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_02` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_03` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_04` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_05` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_06` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_07` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_08` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_09` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_10` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_11` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_12` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_13` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_14` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_15` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_16` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_17` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_18` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_19` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_20` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_21` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_22` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_23` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_24` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_25` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_26` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_27` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_28` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_29` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_30` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_31` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_32` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_33` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_34` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_35` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_36` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_37` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_38` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_39` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_40` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_41` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_42` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_43` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_44` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_45` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_46` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_47` auto_increment = 0;
ALTER TABLE `kanrensha_seijidantai_history_99` auto_increment = 0;

   
DELETE FROM `task_plan_2026`;
ALTER TABLE `task_plan_2026` auto_increment = 0;

DELETE FROM `task_info`;
ALTER TABLE `task_info` auto_increment = 0;
INSERT INTO `task_info` (`task_info_id`,`task_info_code`,`task_info_name`,`is_latest`,`role_list`,`message_start`,`transfer_pass`,`param_query`,`insert_user_id`,`insert_user_code`,`insert_user_name`,`insert_timestamp`,`delete_user_id`,`delete_user_code`,`delete_user_name`,`delete_timestamp`) 
  VALUES 
  (136,317,'サンプルタスク情報',1,'admin,manager','メッセージ','pageUrl','',198,190,'ユーザ','2022-12-05 12:34:56',0,0,'ユーザ','1948-07-28 00:00:00')
  ,(137,318,'サンプルタスク情報',1,'admin,manager','メッセージ','pageUrl','',198,190,'ユーザ','2022-12-05 12:34:56',0,0,'ユーザ','1948-07-28 00:00:00')
  ,(138,319,'サンプルタスク情報',1,'admin,manager','メッセージ','pageUrl','',198,190,'ユーザ','2022-12-05 12:34:56',0,0,'ユーザ','1948-07-28 00:00:00')
  ;
 
